import 'package:dallal_proj/core/entities/media_entity/media_entity.dart';
import 'package:dallal_proj/core/utils/assets_data.dart';
import 'package:dallal_proj/features/details_page/domain/entities/show_details_entity.dart';

class Tst {
  static List<String> imgPaths = [
    AssetsData.vPropertyPng,
    AssetsData.brflHouseJpg,
    AssetsData.bkgImg,
    AssetsData.propertyJpg,
  ];

  static List<ShowDetailsEntity> likedAdsCardModel = [
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
  ];

  static List<ShowDetailsEntity> favedAdsCardModel = [
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
  ];

  static List<ShowDetailsEntity> randomAdsCardModel = [
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',
      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '5',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
  ];

  static List<ShowDetailsEntity> myAdsCardModel = [
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      // package: null,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: false,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: null,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: null,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: false,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: true,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
  ];

  static List<ShowDetailsEntity> premiumAdvs = [
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'دكان',
      isLikedDet: false,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'دكان في السوق التجاري',
      priceDet: '75000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'أرض',
      isLikedDet: true,
      isFavedDet: true,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'قطعة أرض للبيع',
      priceDet: '200000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'شقة',
      isLikedDet: false,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'شقة في حي السبعين',
      priceDet: '50000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
    ShowDetailsEntity(
      advId: '6',
      area: '1200',
      city: 'صنعاء',

      whatsNum: '774123123',
      userId: '7',
      phoneNum: '774188043',
      offerType: 'شقة',
      likes: '10',
      isPended: false,
      isNegot: false,
      fName: 'samia ali',
      dateDet: '2022-12-12',

      isMineDet: false,
      sectionDet: 'منزل',
      isLikedDet: true,
      isFavedDet: false,
      isPrem: true,
      imgs: [
        MediaEntity(
          mediaId: '3',
          mediaUrl:
              'https://dalal.ghassanalmoqbeli.com//api-app//api//media//get_media.php?type=ad_media&file=46_6940a6ff9d614.png',
        ),
      ],
      titleDet: 'بيت ثلاثة دور',
      priceDet: '100000 ريال يمني',
      location: 'صنعاء - شارع المقالح',
      status: true,
    ),
  ];

  static List<String> testNotificList = [
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.\n هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.\n هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار، يظهر للمستخدم عندما يقوم بخطوة ناجحة في المهمة التي يقوم بها.',
    'هذا نص الاشعار،',
  ];
}
